version: 2.1
jobs:
  build:
    docker:
      - image: tiltdev/tilt:latest

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose
      - run: ./test.sh
